[package]
name = "hkk-nixos"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
color-eyre.workspace = true
nix = { version = "0.31.3", default-features = false, features = ["hostname"] }
owo-colors.workspace = true

# Workspace
hkk-arguments.workspace = true
hkk-installable.workspace = true
